# Generated by Django 3.0.6 on 2020-07-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
